language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - android-22
    - build-tools-25.0.0
    - extra-android-m2repository

cache: false
# Use the Travis Container-Based Infrastructure (see #203)
sudo: false

install:
  # Ensure Gradle wrapper is executable, download wrapper and show version
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
  # Download and show android dependencies
  # - ./gradlew androidDependencies

script:
  - ./gradlew clean build connectedCheck
