language: android

jdk:
  - oraclejdk8

android:
  components:

    - android-22
    - build-tools-25.0.0

cache: false
# Use the Travis Container-Based Infrastructure (see #203)
sudo: false

install:
  # Ensure Gradle wrapper is executable, download wrapper and show version
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
  # Download and show android dependencies
  # - ./gradlew androidDependencies

script:
  - ./gradlew clean build connectedCheck
